name: Compilar APK con Python-for-Android

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Descargar el código fuente
      uses: actions/checkout@v4

    - name: Configurar Entorno Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Instalar dependencias de Linux y Python-for-Android
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip autoconf automake libtool pkg-config zlib1g-dev libjpeg-dev python3-pip python3-setuptools libffi-dev libssl-dev
        pip3 install --user --upgrade Cython==0.29.33 virtualenv python-for-android wheel pillow

    - name: Compilar APK Directamente con P4A (Sin Buildozer)
      run: |
        export PATH=$PATH:$HOME/.local/bin
        
        # Forzamos el uso de lo que GitHub ya tiene preinstalado
        export ANDROID_SDK_ROOT=$ANDROID_HOME
        export ANDROID_NDK_ROOT=$ANDROID_NDK_LATEST_HOME
        
        # Le ordenamos usar la API 34 que el entorno reportó como disponible
        p4a apk \
          --private . \
          --package=org.cyberpunk.neolauncherar \
          --name="NeoLauncherAR" \
          --version=1.0 \
          --bootstrap=sdl2 \
          --requirements=python3,kivy==2.3.0,kivymd==1.1.1,pyjnius,pillow \
          --arch=arm64-v8a \
          --android-api=34 \
          --permission=CAMERA \
          --permission=BODY_SENSORS \
          --release

    - name: Subir APK terminada como Artefacto Web
      uses: actions/upload-artifact@v4
      with:
        name: Launcher-AR-Nativo
        path: "*.apk"
