name: Compilar APK con Buildozer

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Descargar el código fuente
      uses: actions/checkout@v4

    - name: Compilar APK usando la Acción Oficial de Buildozer
      uses: ArtemGovorov/buildozer-action@v1
      with:
        buildozer_version: stable
        command: buildozer android debug

    - name: Subir APK terminada como Artefacto Web
      uses: actions/upload-artifact@v4
      with:
        name: Launcher-AR-Debug
        path: bin/*.apk
